# **************************************************************************
# *
# * Authors: Alberto Garcia Mena   (alberto.garcia@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import os

import pyworkflow.protocol.constants as cons
from pyworkflow.utils import Message
from pyworkflow import BETA, UPDATED, NEW, PROD
import pyworkflow.utils as pwutils
import pyworkflow.protocol.params as params
from pwem.protocols import EMProtocol
from pyworkflow.protocol import getUpdatedProtocol
import random
import argparse
import tifffile as tiff
import numpy as np
import xmipp3
import time
import os
from PIL import Image
import mrcfile

SAMPLE_SIZE = 100

class spaLakePopulator(EMProtocol):
    'This protocol will collect the main data from the SPA workflow and push to the SPALake dataBase those data'
    _label = 'SPALake populator '
    _devStatus = BETA

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    # -------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        """ Define the input parameters that will be used."""

        form.addSection(label='Input Screening')
        form.addParam('dataFromScreening', params.EnumParam, default=1,
                      choices=['True', 'False'],
                      display=params.EnumParam.DISPLAY_HLIST,
                      label='Data from the screening',
                      help='True if data from the screening is on the workflow (Smartscope or SmartEPU plugin).')
        form.addParam('Grids', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfGrids',
                      allowsNull=True,
                      label="Grid ",
                      help="Grid used for acquisition")
        form.addParam('Atlas', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfAtlas',
                      allowsNull=True,
                      label="Atlas",
                      help='Atlas used for acquisition')
        form.addParam('Squares', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfSquares',
                      allowsNull=True,
                      label="Squares",
                      help='Squares used on the picker')
        form.addParam('Holes', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfHoles',
                      allowsNull=True,
                      label="Holes",
                      help='Holes used on the acquisition')
        form.addParam('Movies_screening', params.PointerParam,
                      condition='dataFromScreening==0',
                      allowsNull=True,
                      pointerClass='SetOfMoviesSS',
                      label="Movies",
                      help='Movies used on the acquisition generated by the SmartscopeConnection')

        form.addSection(label=Message.LABEL_INPUT)
        form.addParam('Movies', params.PointerParam,
                      condition='dataFromScreening==1',
                      allowsNull=True,
                      pointerClass='SetOfMovies',
                      label="Movies",
                      help='Movies imported by "Import Movies" protocol')

        form.addParam('micrographs', params.PointerParam,
                       pointerClass='SetOfMicrographs',
                       label="Micrographs",
                      allowsNull=True,
                       help='Micrographs generated by aligner')
        form.addParam('TotalClasses2D', params.PointerParam,
                       pointerClass='SetOfClasses2D',
                       allowsNull=True,
                       label="Total Classes2D ",
                       help='Set of the Classes2D ')
        form.addParam('goodClassesOrigin', params.EnumParam, default=0,
                      choices=['Xmipp/Relion', 'Cryoasses', 'Manual'],
                      display=params.EnumParam.DISPLAY_HLIST,
                      label='Protocol generates the good 2D classes',
                      help='Select the protocol the good classes come from. Xmipp and Relion generates setOfClasses2D, Cryoasses SetOfAverages, manual selection generates SetOfClasses2D.')
        form.addParam('goodClasses2DXmippRelion', params.PointerParam,
                       condition='goodClassesOrigin==0',
                       pointerClass='SetOfClasses2D',
                       allowsNull=True,
                       label="Good Classes2D from Relion",
                       help='Set of good Classes2D calculated by Relion ranker')
        form.addParam('goodClasses2DCryoasses', params.PointerParam,
                       condition='goodClassesOrigin==1',
                       pointerClass='SetOfAverages',
                       allowsNull=True,
                       label="Good Classes2D from Cryoasses",
                       help='Set of good Classes2D calculated by Cryoasses ranker')
        form.addParam('goodClasses2DManual', params.PointerParam,
                      condition='goodClassesOrigin==2',
                      pointerClass='SetOfClasses2D',
                      allowsNull=True,
                      label="Good Classes2D from manual selection",
                      help='Set of good Classes2D from manual selection (protUserSubset')


        form.addParam('volume', params.PointerParam,
                       pointerClass='Volume',
                       allowsNull=True,
                       label="Volume refined",
                       help='Volume refined')

        form.addSection(label=Message.LABEL_EXPORT)
        form.addParam('processingAuthor', params.LabelParam,
                       allowsNull=True,
                       label="Processing author",
                       help='Name of the authors of the processing of the workflow')
        form.addParam('processingDate', params.LabelParam,
                       allowsNull=True,
                       label="Processing date (mm/yy)",
                       help='Date of the processing')

    def _initialize(self):
        # DEBUGALBERTO START
        import os
        fname = "/home/agarcia/Documents/attachActionDebug.txt"
        if os.path.exists(fname):
            os.remove(fname)
        fjj = open(fname, "a+")
        fjj.write('ALBERTO--------->onDebugMode PID {}'.format(os.getpid()))
        fjj.close()
        print('ALBERTO--------->onDebugMode PID {}'.format(os.getpid()))
        import time
        time.sleep(10)
        # DEBUGALBERTO END

    def _insertAllSteps(self):
        initialize = self._insertFunctionStep(self._initialize,
                                 prerequisites=[],
                                 needsGPU=False)
        listObjects = self.listInputs()
        hierarchy = ["Movies_screening", "Movies", "micrographs", "TotalClasses2D", "goodClasses", "volume"]
        print(f'\nhierarchy: {hierarchy}')
        print(f'listObjects: {listObjects}')

        collectMovies = self._insertFunctionStep(self.collectMovies,
                                                 listObjects,
                                                 prerequisites=[initialize],
                                                 needsGPU=False)
        if "Movies_screening" in listObjects:
            collectScreening = self._insertFunctionStep(self.collectScreening,
                                                     prerequisites=[collectMovies],
                                                     needsGPU=False)
        if "micrographs" in listObjects:
            collectMicrographs = self._insertFunctionStep(self.collectMicrographs,
                                                     prerequisites=[collectMovies],
                                                     needsGPU=False)
        if "TotalClasses2D" in listObjects:
            collectCoords = self._insertFunctionStep(self.collectCoords,
                                                            prerequisites=[collectMicrographs],
                                                            needsGPU=False)
            collect2DClasses = self._insertFunctionStep(self.collect2DClasses,
                                                     prerequisites=[collectCoords],
                                                     needsGPU=False)
        if "goodClasses" in listObjects:
            collectGood2DClasses = self._insertFunctionStep(self.collectGood2DClasses,
                                                            listObjects,
                                                            prerequisites=[collect2DClasses],
                                                            needsGPU=False)
        if "volume" in listObjects:
            collectVolume = self._insertFunctionStep(self.collectVolume,
                                                     prerequisites=[collectGood2DClasses],
                                                     needsGPU=False)

    # ----------COLLECTION

    def collectMovies(self, listObjects):
        if 'Movies_screening' in listObjects:
            movies = self.Movies_screening.get()
        else:
            movies = self.Movies.get()

        # MOVIES
        listMovies = list(movies)
        total_size = len(listMovies)
        if total_size <= SAMPLE_SIZE:
            self.selectedMovies  =  listMovies
        else:
            step = total_size / SAMPLE_SIZE
            self.selectedMovies = [listMovies[random.randint(int(i * step), int((i + 1) * step) - 1)] for i in range(SAMPLE_SIZE)]
            #self.selectedMovies =  random.sample(listMovies, SAMPLE_SIZE) #Full random

        # ACQUISITION
        movieToExtract = self.selectedMovies[0]
        acq = movieToExtract.getAcquisition()
        self.voltaje = acq.getVoltage()
        self.dosePerFrame=acq.getDosePerFrame()
        self.frames = movieToExtract.getFramesRange()[1]
        self.extension = movieToExtract.getBaseName().split('.')[-1]

        # FRAMES
        self.shapeFrame = []
        for m in self.selectedMovies:
            frame = self.frameExtraction(m)
            self.shapeFrame.append(self.frameShaping(frame))



    def collectScreening(self):
        pass

    def collectMicrographs(self):
        pass

    def collectCoords(self):
        pass

    def collect2DClasses(self):
        pass

    def collectGood2DClasses(self):
        pass

    def collectVolume(self):
        pass


    #----------UTILS
    def listInputs(self):
        listObjects = []

        if self.volume.hasValue() == True:
            listObjects.append('volume')
        if self.goodClasses2DXmippRelion.hasValue() == True:
            listObjects.append('goodClasses')
            listObjects.append('goodClasses2DXmippRelion')
        if self.goodClasses2DCryoasses.hasValue() == True:
            listObjects.append('goodClasses')
            listObjects.append('goodClasses2DCryoasses')
        if self.goodClasses2DManual.hasValue() == True:
            listObjects.append('goodClasses')
            listObjects.append('goodClasses2DManual')
        if self.TotalClasses2D.hasValue() == True:
            listObjects.append('TotalClasses2D')
        if self.micrographs.hasValue() == True:
            listObjects.append('micrographs')
        if self.Movies_screening.hasValue() == True:
            listObjects.append('Movies_screening')
            listObjects.append('Movies')
            if self.Holes.hasValue() == True:
                listObjects.append('Holes')
            if self.Squares.hasValue() == True:
                listObjects.append('Squares')
            if self.Atlas.hasValue() == True:
                listObjects.append('Atlas')
            if self.Grids.hasValue() == True:
                listObjects.append('Grids')
        elif self.Movies.hasValue() == True:
            listObjects.append('Movies')

        return listObjects

    def frameExtraction(self, movie):
        '''
        Extract a single frame the midle one, for any kind of movie, *.tif, *.mrc, *.eer
        For eer extract to have a dose of 1e-/A2'''
        #self.voltaje self.dosePerFr self.frames self.extension
        pathMovie = os.path.join(os.getcwd(),  movie.getLocation()[1])
        frame_index = int(self.frames / 2)
        if self.extension in ["tif", "tiff"]:
            with tiff.TiffFile(pathMovie) as tif:
                frame = tif.pages[frame_index].asarray().astype(np.float16)
        elif self.extension == "mrc":
            with mrcfile.open(pathMovie, permissive=True) as mrc:
                data = mrc.data.astype(np.float16)
                frame = data[frame_index]
        elif self.extension == 'eer':
            nameFramePath = os.path.join(os.getcwd(), self._getExtraPath(), movie.getBaseName().replace('.eer', '_middleFrame.tif'))
            framesNum = 100
            frame_index= 50
            cmd = f'{frame_index}@{pathMovie}#{framesNum},4K,uint8 -o {nameFramePath}'
            self.runJob('xmipp_image_convert', cmd, env=xmipp3.Plugin.getEnviron())

    def frameShaping(self, frame):
        'Crop, Resize and Normalize 0-0; 10-255'
        pass
    # ----------GENERAL-UTILS

    def _summary(self):
        summary = []
        summaryF = self._getExtraPath("summary.txt")
        if not os.path.exists(summaryF):
            summary.append("No summary file yet.")
        else:
            summaryF = open(summaryF, "r")
            for line in summaryF.readlines():
                summary.append(line.rstrip())
            summaryF.close()
        return summary

    def _validate(self):
        errors = []
        listObjects = self.listInputs()

        def validate_list(obj_list):
            hierarchy = ["Movies", "micrographs", "TotalClasses2D", "goodClasses", "volume"]
            elements = set(obj_list)

            # Check hierarchical dependencies
            for i, item in enumerate(hierarchy):
                if item in elements:
                    missing = [prev for prev in hierarchy[:i] if prev not in elements]
                    if missing:
                        return False, f"Missing dependencies for '{item}': {missing}"

            # Special rule: Movies_screening requires extra objects
            if "Movies_screening" in elements:
                required = {"Grids", "Atlas", "Squares", "Holes"}
                missing = required - elements
                if missing:
                    return False, f"Movies_screening requires: {list(missing)}"

            return True, "OK"

        valiodator = validate_list(listObjects)
        if valiodator[0] == False:
            errors.append(valiodator[1])

        return errors